# Generated by Django 5.0.1 on 2024-01-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id_type_assurance',
        ),
    ]
