# Generated by Django 5.0.2 on 2024-02-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_maladie_chronique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Prenom',
            new_name='prenom',
        ),
    ]
