# Generated by Django 5.0.2 on 2024-03-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recherche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recherche',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('termine', 'Terminé'), ('annulee', 'Annulée')], default='en_attente', max_length=255),
        ),
    ]
