# Generated by Django 5.0.2 on 2024-02-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_prenom_client_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='degarde',
            field=models.BooleanField(default=False),
        ),
    ]
