# Generated by Django 5.0.2 on 2024-02-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pharmacie_degarde'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commandetous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordornance', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_medicament', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('en_attente', models.BooleanField(default=True)),
                ('terminer', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('Facture', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('pharmacie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pharmacie')),
            ],
        ),
    ]
