# Generated by Django 5.0.2 on 2024-03-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_date_creation_client_date_modification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('data_id', models.CharField(max_length=255)),
                ('metadata', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('pharmacie', 'Pharmacie')], max_length=255)),
                ('user_id', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
