# Generated by Django 5.0.2 on 2024-02-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_conseil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandetous',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
