# Generated by Django 5.0.2 on 2024-03-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_notification_data_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='logo_url',
            field=models.CharField(default='https://media.istockphoto.com/id/1275720974/vector/blue-and-green-medical-cross-health.jpg?s=612x612&w=0&k=20&c=j322qhLcySdh7qhtlTnUf_EUzlQG2i9bnoJ3vHdJ81I=', max_length=100),
        ),
    ]
