# Generated by Django 5.0.2 on 2024-03-23 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pharmacie_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_client', to='api.client'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacie_user', to='api.pharmacie'),
        ),
    ]
