# Generated by Django 5.0.2 on 2024-11-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_commande_client_alter_conseil_pharmacie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='commune_pharmacie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='logo_url',
            field=models.CharField(default='https://media.istockphoto.com/id/1275720974/vector/blue-and-green-medical-cross-health.jpg?s=612x612&w=0&k=20&c=j322qhLcySdh7qhtlTnUf_EUzlQG2i9bnoJ3vHdJ81I=', max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='num_pharmacie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='numero_contact_pharmacie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='ville_pharmacie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
