# Generated by Django 5.0.2 on 2024-11-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_commande_facture_invoice_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('brouilon', 'Brouillon'), ('envoyee', 'Envoyée'), ('impayee', 'Impayée'), ('payee', 'Payée'), ('echouee', 'Echouée'), ('en_retard', 'En retard')], default='impayee', max_length=10),
        ),
    ]
