# Generated by Django 5.0.2 on 2024-11-12 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_invoice_paid_at_alter_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('number_user', models.CharField(blank=True, max_length=255, null=True)),
                ('name_user', models.CharField(blank=True, max_length=255, null=True)),
                ('email_user', models.CharField(blank=True, max_length=255, null=True)),
                ('country_user', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_total', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('type_transaction', models.CharField(max_length=255, unique=True)),
                ('type_payment', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_item', to='api.invoice')),
            ],
        ),
    ]
