# Generated by Django 5.0.2 on 2024-11-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_invoicepayment_currency_alter_invoicepayment_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='type_transaction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
