# Generated by Django 5.0.2 on 2024-11-23 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_commande_recherche_alter_commande_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_client', to='api.client'),
        ),
    ]
