# Generated by Django 5.0.2 on 2024-12-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_invoice_code_recu'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='amount_receive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='fees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
