# Generated by Django 5.0.2 on 2024-12-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_invoicepayment_amount_receive_invoicepayment_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepayment',
            name='country_user',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='email_user',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='name_user',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='number_user',
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='customer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
