# Generated by Django 5.0.2 on 2024-12-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_remove_invoicepayment_country_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="nom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="prenom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="commande",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("traite", "Traité"),
                    ("en_attente_livraison", "En attente de livraison"),
                    ("en_cours", "En cours de livraison"),
                    ("livree", "Livrée"),
                    ("termine", "Terminé"),
                    ("annulee", "Annulée"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
