# Generated by Django 5.0.2 on 2025-01-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_walletpharmacie_walletpharmaciehistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="walletpharmaciehistory",
            old_name="type",
            new_name="action_type",
        ),
        migrations.AddField(
            model_name="walletpharmaciehistory",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
