# Generated by Django 5.0.2 on 2025-01-04 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_rename_type_walletpharmaciehistory_action_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletpharmaciehistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet_pharmacie_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
