# Generated by Django 5.0.2 on 2025-01-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_walletpharmaciehistory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="service_fees",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
